# Generated by Django 6.1.1 on 2026-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('renovation', 'Renovation')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Enter project features, one per line.'),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('design_concept', 'Design Concept')], default='design_concept', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='plot_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_type',
            field=models.CharField(choices=[('design', 'Design'), ('construction', 'Construction'), ('renovation', 'Renovation'), ('advisory', 'Advisory'), ('facility_management', 'Facility Management'), ('property_trading', 'Property Trading')], max_length=30),
        ),
    ]
